CREATE DATABASE ActividadClase08;
GO 

USE ActividadClase08;

CREATE TABLE Cuenta(
	DNI_TITULAR BIGINT UNIQUE NOT NULL,
	NOMBRE_TITULAR VARCHAR(100) NOT NULL,	
	SALDO DECIMAL(10,2),
	CONSTRAINT PK_CUENTA PRIMARY KEY(DNI_TITULAR)
);

CREATE TABLE Historial_Transferencias(
	DNI_CUENTA_ORIGEN BIGINT NOT NULL,
	DNI_CUENTA_DESTINO BIGINT NOT NULL,
	MONTO DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_HISTORIAL_TRANSFERENCIAS PRIMARY KEY(DNI_CUENTA_ORIGEN,DNI_CUENTA_DESTINO,FECHA)
);

ALTER TABLE Historial_Transferencias ADD 
CONSTRAINT FK_HISTORIAL_TRANSFERENCIAS_CUENTA
FOREIGN KEY(DNI_CUENTA_ORIGEN) REFERENCES Cuenta(DNI_TITULAR),
FOREIGN KEY(DNI_CUENTA_DESTINO) REFERENCES Cuenta(DNI_TITULAR);

ALTER TABLE Cuenta DROP COLUMN Fecha;

INSERT INTO Cuenta VALUES(65489641, 'Juan Alberto Perez', 150000),(35126498, 'Pablo Omar Valdez', 100000);



SELECT saldo FROM Cuenta WHERE DNI_TITULAR = 35126498;


DECLARE @montoDebitar DECIMAL(10,2);
SET @montoDebitar = 50000;

DECLARE @dniReceptor BIGINT;
SET @dniReceptor = 65489641;

UPDATE Cuenta SET SALDO = SALDO - @montoDebitar WHERE DNI_TITULAR = @dniReceptor;

SELECT COUNT(*) FROM Cuenta WHERE DNI_TITULAR = 65389641; 

SELECT 

SELECT * FROM Cuenta;

